version: '3'
services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/talentsite
      - JWT_SECRET=devsecret
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - '3001:5000'
    depends_on:
      - mongo
  web:
    build: ./web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - '3000:3000'
    depends_on:
      - server
